name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
  workflow_dispatch: {}
  schedule:
    - cron: "30 1 * * *"

jobs:
  release:
    runs-on: ubuntu-20.04
    env:
      GITHUB_REF: ${{ github.ref }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          sudo apt-get update && sudo apt-get install -y transifex-client gettext
          sudo pip install -r requirements.txt

      - name: Push translations
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          set -e

          make gettext
          if [[ -z "${TX_TOKEN}" ]]; then
            echo "TX_TOKEN not set, skip tx pull"
          else
            tx push -s
          fi
          make clean

      - name: Pull translations
        run: |
          set -e

          if [[ -z "${TX_TOKEN}" ]]; then
            echo "TX_TOKEN not set, skip tx pull"
          else
            make transifex_pull
          fi

      - name: Build docs
        run: |
          set -e
          docker build -t builder . -f .docker/Dockerfile
          docker run -v $(pwd):/io/data builder /io/data/.docker/docker-build.sh


      - name: Commit to the QField repository
        uses: drud/action-cross-commit@master
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        with:
          source-folder: build/html
          destination-repository: https://<user>:${{ secrets.QFIELD_FAIRY_TOKEN }}@github.com/opengisch/QField.git
          destination-folder: docs
          destination-branch: gh-pages
          git-user: "opengisch"
          git-user-email: info@opengis.ch
          git-commit-message: "Automatic doc update https://github.com/opengisch/QField-docs/commit/${{ github.sha }}"


