name: gh-pages
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 1 * * *'

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9  # transifex-client has compatibility problem with 3.10
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install requirements insiders
        run: pip install -r requirements-insiders.txt
        env:
          MKDOCS_INSIDERS_TOKEN: ${{ secrets.MKDOCS_INSIDERS_TOKEN }}
      - name: Configure transifex
        run: |
          tx add remote \
            --file-filter 'translations/<project_slug>.<resource_slug>/<lang>.<ext>' \
            https://www.transifex.com/opengisch/qfield-documentation/dashboard/
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Push translations
        run: |
          tx push -s
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Pull translations
        run: |
          tx pull --all
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_LANGUAGE_ONLY: false
