name: gh-pages
on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the container and the docs inside of it
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
        run: |
          docker build . --build-arg tx_token=$TX_TOKEN -t qfield-docs
          mkdir site
          docker run -v "${PWD}/site:/opt/app/site" qfield-docs

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9  # transifex-client has compatibility problem with 3.10

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Install requirements insiders
        run: pip install -r requirements-insiders.txt
        env:
          MKDOCS_INSIDERS_TOKEN: ${{ secrets.MKDOCS_INSIDERS_TOKEN }}

      - name: Deploy documentation
        run: mkdocs gh-deploy -d ./site --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_LANGUAGE_ONLY: false
