name: gh-pages
on:
  push:
    branches: 
      - mkdocs
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Download translations
        run: tx pull --all
        env:
          TX_TOKEN: ${{ secrets.TX_TOKEN }}
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
